repos:
- repo: local
  hooks:
  - id: commit-msg
    name: Commit messages with work Item
    language: script
    entry: commit-msg
    stages: [commit-msg]
  - id: branch-naming-policy
    name: Branch Naming Policy
    language: script
    entry: branch-policy
    pass_filenames: false
  - id: submodule-init
    name: submodule-init
    language: script
    entry: submodule-init
    pass_filenames: false
    always_run: true
    stages: [post-checkout]
